title: "BlogDev"
#theme: jekyll-theme-cayman

# Author Settings
author: Pierre V # add your name
author-img: pierre-v.jpg # add your photo
about-author: Je suis un développeur qui partage mes connaissances et qui ne cesse jamais d'apprendre. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: pierreV5931 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"
